markdown:         kramdown
highlighter:      true
paginate:         6
permalink:        /:title
gems:             [jekyll-paginate]

title:            XiaoGuo's Site
url:              http://guozesheng.github.io
author:
    name:         Guo Zesheng
    email:        <a href="mailto:guozesheng@gmail.com">guozesheng@gmail.com</a>
description:      "XiaoGuo\'s Site"
author_info:      <a href="http://guozesheng.github.io/about">XiaoGuo</a>

copyright:
    - Design by <a href="http://guozesheng.github.io/about" title="XiaoGuo" target="_blank">XiaoGuo</a> &copy; 2017
